name: Multiplication Pipeline

on:
  push:
    branches:
      - main

jobs:
  calculator:

    runs-on: ubuntu-latest

    steps:

      - name: Multiplication
        run: |
          a=15
          b=20
          mul=$((a*b))
          echo "Mul = $mul"
